### ISSUE TITLE
Snorlax Reloaded on the Xposed Module Repository

### ISSUE THREAD

**Issue by mhetralla** [alucas/Snorlax#15]
Thanks for updating the module. I've been using [PoGoIV](http://repo.xposed.info/module/de.chuparch0pper.android.xposed.pogoiv) + [Pokemon GO direct MitM ](http://repo.xposed.info/module/com.elynx.pogoxmitm) for a long time, but they were not updated to the latest version, and daily prizes and buddies had problems. I miss some features from those modules, but I hope that in the future Snorlax can be worked on to add them.

The issue I want to report is: In the Xposed Module Repository, the [Snorlax Reloaded module](http://repo.xposed.info/module/com.alucas.snorlax) can't be installed because the installer is expecting the package **com.alucas.snorlax** and it receives a package named **com.icecream.snorlax**.

**Comment by alucas** [comment]
Yeah I'm aware of that problem.
I will probably have change the package's name of all the classes of this projet to fix this.

**Comment by alucas** [comment]
What features are you missing from these modules ? ;)

**Comment by mhetralla** [comment]
Oh, I've using this module many weeks now, and I miss this things:

- When [we fail a catch](http://i.imgur.com/suWV1xp.png) or [the mon flees](http://i.imgur.com/KQfA1lH.png), show the percentage of the probability we had of that to happen.

- Show the IVs inside circles, [using this Unicodes](http://www.unicode.org/charts/beta/nameslist/n_2460.html). That makes the IVs more visible and uses a lot less characters.

- Grade perfection: Add a format to sum up the IV percentage to a letter. (A:100%-91%, B:89%-80%...) Example of the last two features: [Snorlax](http://i.imgur.com/7veyqoV.png), [Pokemon GO direct MitM](http://i.imgur.com/FFilOCz.png)

- Show Pokéstop spin information & number of items in bag. Useful to see the chain Pokéstop you are, and to check the items when you spin and exit the stop too fast and it seems that failed. [Heads-up notification](http://i.imgur.com/eMY6qI3.png), [notification](http://i.imgur.com/Rl7APXP.png).

- When an egg is hatched, show info about the mon hatched (name, CP, IV, candies and dust received), even when the hatch animation has not played yet.

- Gym info. PoGoIV did this with a scrollable notification when you entered a gim, with CP, moves and IV of each mon.

- Not related to the other modules, because this feature is exclusive of this one, but if you have the **Enable dismiss notifications** enabled, the notification dismiss immediately, as intended. I would like the notification to be dismissed when the animation ends, because when I'm waiting to end I like to see the stats of what I just catched. Maybe adding some delay to dismiss it?

Here you have the GitHub of the another modules, maybe you can cherrypick stuff from there: [PoGoIV](https://github.com/chuparCh0pper/PoGoIV_xposed) and [Pokemon GO direct MitM](https://github.com/ELynx/pokemon-go-xposed-mitm).

**Comment by alucas** [comment]
`When [we fail a catch](http://i.imgur.com/suWV1xp.png) or [the mon flees](http://i.imgur.com/KQfA1lH.png), show the percentage of the probability we had of that to happen.`

The flee rate is fix, it's already displayed in the notification (the little green circle, with an arrow)
The catch rate is also displayed, but it doesn't take account of the berry/curve/great throw. I suppose I can add that.

`Show the IVs inside circles, [using this Unicodes](http://www.unicode.org/charts/beta/nameslist/n_2460.html). That makes the IVs more visible and uses a lot less characters.`

Yeah I knew about those. I planned to add them (in my head) but it was not a priority. But I will add them on day :p

`Grade perfection: Add a format to sum up the IV percentage to a letter. (A:100%-91%, B:89%-80%...) Example of the last two features: [Snorlax](http://i.imgur.com/7veyqoV.png), [Pokemon GO direct MitM](http://i.imgur.com/FFilOCz.png)`

No problem. I can add that!

`Show Pokéstop spin information & number of items in bag. Useful to see the chain Pokéstop you are, and to check the items when you spin and exit the stop too fast and it seems that failed. [Heads-up notification](http://i.imgur.com/eMY6qI3.png), [notification](http://i.imgur.com/Rl7APXP.png).`

Good idea, I had no plan to add anything on the pokestop, but there is probably some interesting information that that to show! :)

`When an egg is hatched, show info about the mon hatched (name, CP, IV, candies and dust received), even when the hatch animation has not played yet.`

I think that was done by Snorlax at one point, I can see trace of that in the code/history. Don't know why it was removed.

`Gym info. PoGoIV did this with a scrollable notification when you entered a gim, with CP, moves and IV of each mon`

Yep, I will look at that.


Thx for the idea :)

**Comment by alucas** [comment]
ce0fe86fc6c3629ecc1dd480032aadc944329134
