### ISSUE TITLE
Virus detection of Avast!

### ISSUE THREAD

**Issue by syui** [alucas/Snorlax#16]
[abast](https://play.google.com/store/apps/details?id=com.avast.android.mobilesecurity)

It is certified as dangerous software. Where is the reason considered to be? It was not detected in the previous Snorlax.

**Comment by alucas** [comment]
As "Last version" you mean the 1.6.0 ? Or the 1.4.0 from igoticecream ?

**Comment by syui** [comment]
During installation: 1.60 and 1.4.0

**Comment by syui** [comment]
It is no longer displayed.  1.7.0
