### ISSUE TITLE
Pokemon unplayable with Snorlax enabled

### ISSUE THREAD

**Issue by danizwam** [alucas/Snorlax#23]
Hi, 

since yesterday,  Snorlax Reloaded is no longer working properly. 

Pogo does not show Pokémon or Pokestops after startup. After several minutes, the Gyms appear, but no wild Pokemon, only shadows on the ground. The Pokémon in Gyms are glowing orbs. 

The original Snorlax works!

**Comment by alexcheveau** [comment]
https://twitter.com/PokemonGoApp/status/804398573278339073

**Comment by danizwam** [comment]
Interesting, but why does it work with the old Snorlax or Snorlax Reloaded deactivated? I rebooted several times and i had the delay only wird SR activated.

**Comment by alucas** [comment]
Hum, I'm not able to reproduce your bug. I don't have any problem to play pogo with any version of Snorlax. Do you still have that bug ?

**Comment by danizwam** [comment]
I switched again to SR and it seems to work again. Must have been a weired coincidence that caused this bug :/ Believe me, i installed and reinstalled Snorlax and SR and several times and every time, i started with SR, i had this bug :/
