### ISSUE TITLE
Any extra banning chance over the "original" Snorlax module?

### ISSUE THREAD

**Issue by febs** [alucas/Snorlax#24]
Pardon my ignorance, but I'd like to know if by using this version of Snorlax and its extra features there is any chance by whom Niantic could detect that it is used and behave consequently, especially compared with the xposed module of igoticeream from which this forked from.

Thanks so much!

**Comment by alucas** [comment]
Hi,

Most of the feature are actually read-only, the module only scan the network and launch some Android alert (notification, toast, ...)
The only two features that might possibly be seen by the client (and not the server) are the Rename (that already exist in Snorlax legacy) and Lure (added in my fork).

We don't, in any way, modify the PokemonGo APK (like pogo++ on IOS).

So if you trusted the legacy version, don't worry to much! ;)

**Comment by febs** [comment]
The client and not the server. Well, unless the client doesn't send those informations back.

**Comment by alucas** [comment]
Of course. ;)
