### ISSUE TITLE
Can't build dev branch

### ISSUE THREAD

**Issue by febs** [alucas/Snorlax#25]
I get plenty of errors, the first one being:

Note: Generating a Provider for com.icecream.snorlax.module.feature.mitm.MitmProvider. Prefer to run the dagger processor over that class instead.
/home/fabio/devel/others/Snorlax/app/src/main/java/com/icecream/snorlax/module/feature/gym/Gym.java:19: error: package POGOProtos.Data.Gym.GymMembershipOuterClass does not
 exist

Thanks

**Comment by alexcheveau** [comment]
No errors here neither on Travis
https://travis-ci.org/alucas/Snorlax/builds/180460692

**Comment by alucas** [comment]
did you init the submodules ?

    git submodule update --init

**Comment by febs** [comment]
My bad. It is now building!
