### ISSUE TITLE
Dev Branch

### ISSUE THREAD

**Issue by alexcheveau** [alucas/Snorlax#28]
Hey lucas, dev branch build apk is much smaller 1213kb > 1553kb and it's not working for me (just did a pull)
What i'm missing

**Comment by alexcheveau** [comment]
Did another pull and builded with
            buildToolsVersion         : '25.0.1',
            compileSdkVersion         : 25,
            targetSdkVersion          : 25,

All good here :D
Including my personal pref for the headsup
![screenshot_20161211-174737](https://cloud.githubusercontent.com/assets/6544130/21082802/0bd8c930-bfca-11e6-8207-0d29c2a05553.png)

**Comment by alucas** [comment]
Please create a new issue to express that need ;)
