### ISSUE TITLE
[Idea] Headsup: Show EvolvedCP on mons that can be evolved

### ISSUE THREAD

**Issue by alexcheveau** [alucas/Snorlax#32]
I just wrote the code, gona upload later i'm still testing.

![screenshot_20161212-201909](https://cloud.githubusercontent.com/assets/6544130/21138883/522a9ec4-c117-11e6-959c-9304d94859a4.png)

**Comment by alexcheveau** [comment]
Yeah, behold my 91% IV super cp dodrio :D

![screenshot_20161213-093613](https://cloud.githubusercontent.com/assets/6544130/21138964/b67c43dc-c117-11e6-85e8-bbb35211d7e4.png)

**Comment by alucas** [comment]
Perhaps we need to use the same system as for the rename feature. Let the trainer chose his Format.
