### ISSUE TITLE
Toggle Xposed

### ISSUE THREAD

**Issue by Rootkit-** [alucas/Snorlax#33]
Since this isn't your Mod but it requires this to function I thought this would be ok place... 
When I toggle off and do a soft reboot the Snorlax (both of the versions) module doesn't work.
Combos I've tried:

Xposed 86.1 Wanam + PHH + Magisk 9

Xposed 86.1 Wanam + SuperSU + SuHide.... (also if I install suhide after xposed it fails) (toggle root off after)

Xposed 86.1 wanam + SuperSU (toggle root off after)

So I can get Pokemon to work just not the module

**Comment by alucas** [comment]
I don't really know how to help ^^
I think /r/pokemongodev or the XDA forum are a better place seek help for bypassing Pokemon Go protection :)

**Comment by mhetralla** [comment]
Have you tried using Xposed 86.2 Systemless?

**Comment by alberturer** [comment]
Maybe this (https://www.reddit.com/r/pokemongodev/comments/58gnq3/root_bypass_the_new_update_leads_repost/) can help you.
