### ISSUE TITLE
Update README.md to an updated format details page

### ISSUE THREAD

**Issue by andrikos** [alucas/Snorlax#37]
The current README.md file, on "Replace pokemons name with custom formats (details) :", leads to an outdated wiki page. There should be a new page with all the new extensions present

**Comment by alucas** [comment]
Yep, it's something I wanted to do but I keep procrastinating. Those information are present in the module, and they are up to date.

**Comment by andrikos** [comment]
If you need help, I can create the file and then send a merge request, any preference on where it should be located?

**Comment by alucas** [comment]
Yep, you can help ;)

Update this page : https://github.com/alucas/Snorlax/wiki/Rename-formats
Use those informations for reference : https://github.com/alucas/Snorlax/blob/master/app/src/main/res/values/strings.xml#L24

**Comment by andrikos** [comment]
done :)
