### ISSUE TITLE
Change %nick% to nickname not pokemon name.

### ISSUE THREAD

**Issue by FakeKitten** [alucas/Snorlax#5]
Currently %nick% only shows a pokemon's real name but, personally, I think it would make more sense to have it show whatever the pokemon has been nicknames.

PS, thank you for keeping this module alive :) Notification changes are great and use of emoji is very clever.

**Comment by alucas** [comment]
Good Idea, thx

**Comment by alucas** [comment]
@c490ebbcdb171e2448b4cbbfd8e273081b40d7aa
