### ISSUE TITLE
No stats for Ditto.

### ISSUE THREAD

**Issue by FakeKitten** [alucas/Snorlax#6]
For some reason dittos name just shows as "ditto" in pokemon list.

**Comment by alexcheveau** [comment]
Same here

**Comment by alucas** [comment]
I don't have any ditto on my account to test, but do you display Move information with the rename feature ? because ditto move are not currently supported, so that may make the app functionality crash.

**Comment by alexcheveau** [comment]
I'm using MVT1 / MVT2 / LVL / IV and the name are showing "Ditto"

**Comment by alexcheveau** [comment]
Changed to LVL / IV and it work, showing L28i49
So the prob is indeed with the MVT1 / MVT2

**Comment by zakijesk** [comment]
it's the moves I have it show the level IVs percentage then attack defense hp and it works fine

**Comment by alucas** [comment]
It's already fixed in the **dev** branch, I will release that soon. Also Snorlax now automatically discover the new moves added by Niantic, so those problems must no appear anymore.

**Comment by jane0815** [comment]
Can't wait for new version! Thx @alucas

**Comment by alucas** [comment]
ccb14f4918ab8858fd49ebb0e041b62b26e73e40
