### ISSUE TITLE
[Idea] Heads up notification option

### ISSUE THREAD

**Issue by alexcheveau** [alucas/Snorlax#9]
Option to show IV Stats over Flee Hate
And, if possible, Move Names over Catch Chance

Like: IV 44% [10a/15d/11s] Mud Shot/Water Pulse

_Catch Chance is kind of useless unless you can calc all the modifiers like curve, pokeball type, medals, etc_

**Comment by FakeKitten** [comment]
Personally I really like the current layout of the notifications. Catch rate is useful as it gives a general idea of how hard something will be to catch. 

Best thing would be to add option in settings as a switch between current layout and the one suggested here imo.

**Comment by alucas** [comment]
The idea is to have the most important information for the __capture__ in the little notification. Keep in mind that the space is limited!

**Comment by alexcheveau** [comment]
Personally, I don't care about Catch Chance for 2 reasons: 
1-You can tell by the color of the circle. 2-By the reasons i wrote in the op. 
I guess this is really personal and maybe it's best to leave as it is.
